name: cbz_pdf_tools
description: Offline app to convert CBZ to PDF, merge PDFs (quick/advanced), and rename. Material 3 UI.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.0.0
  path_provider: ^2.0.18
  open_filex: ^4.5.2
  share_plus: ^8.0.0
  file_saver: ^0.0.6
  archive: ^4.0.7
  pdf: ^3.11.3
  native_pdf_renderer: ^5.0.0+1
  reorderables: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true